export const dataAssistant = [
  {
    kepalaLab: {
      id: "1",
      image: "/assets/images/struktur/pakyudi.png",
      role: "Kepala Laboratorium",
      name: "Yudi Irawan Chandra S.kom,MMsi",
      date: "2018 - Sekarang",
    },
    assistan: [
      {
        id: "2",
        image: "/assets/images/struktur/iman.png",
        role: "Staff Laboratorium",
        name: "Imanuel Yehezkiel S.",
        date: "2024 - Sekarang",
      },
      {
        id: "3",
        image: "/assets/images/struktur/indah.png",
        role: "Staff Laboratorium",
        name: "Indah Faradila",
        date: "2024 - Sekarang",
      },
      {
        id: "4",
        image: "/assets/images/struktur/ayatul.png",
        role: "Staff Laboratorium",
        name: "Ayatull Rahman Nikola",
        date: "2025 - Sekarang",
      },
      {
        id: "5",
        image: "/assets/images/struktur/aiesha.png",
        role: "Asisten Aktif",
        name: "Aieshe Phoebe A.",
        date: "2024 - Sekarang",
      },
      {
        id: "6",
        image: "/assets/images/struktur/artha.png",
        role: "Asisten Aktif",
        name: "Artha Graceva",
        date: "2024 - Sekarang",
      },
      {
        id: "7",
        image: "/assets/images/struktur/atifah.png",
        role: "Asisten Aktif",
        name: "Atifah Khairunnisa",
        date: "2024 - Sekarang",
      },
      {
        id: "8",
        image: "/assets/images/struktur/laura.png",
        role: "Asisten Aktif",
        name: "Laura Alysa N.T.",
        date: "2024 - Sekarang",
      },
      {
        id: "9",
        image: "/assets/images/struktur/ical.png",
        role: "Asisten Aktif",
        name: "Muhamad Faisal Basri",
        date: "2025 - Sekarang",
      },
      {
        id: "10",
        image: "/assets/images/struktur/genaro.png",
        role: "Asisten Aktif",
        name: "Ezraeld Genaro Talapessy",
        date: "2025 - Sekarang",
      },
      {
        id: "11",
        image: "/assets/images/struktur/kemas.png",
        role: "Asisten Aktif",
        name: "Kemas Ikhsan Kamil",
        date: "2025 - Sekarang",
      },
      {
        id: "12",
        image: "/assets/images/struktur/farhan.png",
        role: "Asisten Aktif",
        name: "Farhan Fadhlurrahman",
        date: "2025 - Sekarang",
      },

      // data anak baru
      {
        id: "13",
        image: "/assets/images/struktur/AGRA.png",
        role: "Asisten Aktif",
        name: "Agra Arifyasa",
        date: "2026 - Sekarang",
      },
      {
        id: "14",
        image: "/assets/images/struktur/IBRAHIM.png",
        role: "Asisten Aktif",
        name: "Ibrahimovic Sheva",
        date: "2026 - Sekarang",
      },
      {
        id: "15",
        image: "/assets/images/struktur/ABYAN.png",
        role: "Asisten Aktif",
        name: "Abyan Muhammad Farhan",
        date: "2026 - Sekarang",
      },
      {
        id: "16",
        image: "/assets/images/struktur/LUTFI.png",
        role: "Asisten Aktif",
        name: "Muhammad Lutfi Darmawan",
        date: "2026 - Sekarang",
      },
      {
        id: "17",
        image: "/assets/images/struktur/DANA.png",
        role: "Asisten Aktif",
        name: "Dana Hartha Sandiraja",
        date: "2026 - Sekarang",
      },
      {
        id: "18",
        image: "/assets/images/struktur/ROSI.png",
        role: "Asisten Aktif",
        name: "Muhammad Rosi Fahmi",
        date: "2026 - Sekarang",
      },
      {
        id: "19",
        image: "/assets/images/struktur/ayatul.png",
        role: "Asisten Aktif",
        name: "Faradila Laela Putri ",
        date: "2026 - Sekarang",
      },
      
      // {
      //   id: "23",
      //   image: "",
      //   role: "",
      //   name: "",
      //   date: "",
      // },
    ],
  },
];
